describe('UI journey', () => {
  beforeEach(() => {
    cy.visit('http://localhost:3000/')
  })

  const user = Math.floor(Math.random() * 1000)
  const name = `Cypress${user}`

  it.only('signs up a new user', () => {
    cy.wait(2000)
      .get('button[type=submit]')
      .click()
      .wait(1000)
      .get('form')
      .contains('Please, enter your email address.')
      .focused()
      .type(`${name}@ciceroic.com`)
      .get('button[type=submit]')
      .click()
      .wait(1000)
      .get('form')
      .contains('Please, enter your password.')
      .focused()
      .type('Cypress')
      .get('button[type=submit]')
      .click()
      .wait(1000)
      .get('form')
      .contains(
        'Sorry, this email has not been found. If you are a new user, please, click the "Sign Up"-button to register.'
      )
      .get('a[name=signUp]')
      .click()
      .wait(1000)
      .get('button[type=submit]')
      .click()
      .get('form')
      .contains('Please, enter a valid password with at least 8 characters.')
      .focused()
      .type('Cypress')
      .wait(1000)
      .get('button[type=submit]')
      .click()
      .get('form')
      .contains('Please, enter your first name.')
      .focused()
      .type(name)
      .wait(1000)
      .get('button[type=submit]')
      .click()
      .get('form')
      .contains('Please, enter your last name.')
      .focused()
      .type(name)
      .wait(1000)
      .get('button[type=submit]')
    // .click()
  })
})
