describe('UI journey', () => {
  beforeEach(() => {
    cy.visit('http://localhost:3000/')
  })

  it('gets the first video element and plays and pauses it', () => {
    cy.wait(2000)
      .get('video')
      .then(video => {
        const element = video.get(0)
        element.muted = true
        element.play()
        return video
      })
      .wait(5000)
      .get('video')
      .then(video => {
        const element = video.get(0)
        element.pause()
      })
  })
  it.only('evaluates the first speech', () => {
    cy.wait(1000)
      .get('a')
      .first()
      .click()
      .wait(1000)
      .get('button[type=submit]')
      .scrollIntoView()
      .wait(1000)
      .click()
      .wait(2000)
      .get('input[type=submit]')
      .click()
      .get('input[name="first name"]')
      .type('Cypress First Name')
      .get('button[type=submit]')
      .click()
      .wait(2000)
      .get('input[type=submit]')
      .click()
      .get('input[name="last name"]')
      .type('Cypress Last Name')
      .get('input[type=range]')
      .each(input => {
        cy.get(input)
          .invoke('val', Math.floor(Math.random() * 5 + 1))
          .trigger('change')
      })
      .wait(1000)
      .get('button[type=submit]')
      .click()
      .wait(2000)
      .get('input[type=submit]')
      .click()

    // .get('input[type=range]')
    // .first()
    // .invoke('val', 1)
    // .trigger('change')
  })
})
